In [1]:
# Часть 1 Работа с библиотекой NumPy
try: # Провирим установку библиотеки numpy 
    import numpy as np
    print("Библиотека numpy установлена")
except ImportError:
    print("Библиотека numpy не установлена")

Библиотека numpy установлена


In [2]:
matrix = np.zeros((8, 8), dtype=int) # Задача №1. Создаем матрицу размером 8х8 состоящую из 0
matrix[0::2, 1::2] = 1  # Заполняем единицами четные строки и нечетные столбцы используя срезы
matrix[1::2, 0::2] = 1  # Заполняем единицами нечетные строки и четные столбцы используя срезы
print(f'Матрица заполненная единицами в шахматном порядке: ')
print(matrix) # Вывод матрицы на экран
np.savetxt('matrix.txt', matrix, fmt='%d') # Сохранение матрицы в файл

Матрица заполненная единицами в шахматном порядке: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
vector = np.random.normal(0, 5, 2000) # Задача №2. Генерируем вектор: 2000 случайных величин, МО=0, дисперсия 0
print(f'Математическое ожидание: {np.mean(vector)}') # Вывод математического ожидания
print(f'Дисперсия: {np.var(vector)}') # вывод дисперсии

Математическое ожидание: 0.0004535631302534959
Дисперсия: 23.486958663268975
